import type { Dictionary } from "@/lib/i18n";

export const en: Dictionary = {
  lang: "en",
  meta: {
    titleHome: "Hansolow Entertainment | Tour Support and Stage Construction",
    descriptionHome:
      "Freelance tour support, stage construction and production support for touring, festivals, TV productions and trade shows across Germany and internationally.",
    titleAbout: "About | Hansolow Entertainment",
    descriptionAbout:
      "Hans Schröder Salowski – freelance stage construction and production support professional with practical experience in touring and TV productions.",
    titleServices: "Services | Hansolow Entertainment",
    descriptionServices:
      "Stage construction, tour support, festival support, TV production support, event support, Lighting Support and trade show construction – available on a project basis.",
    titleExperience: "Experience | Hansolow Entertainment",
    descriptionExperience:
      "Touring productions, TV productions, major events and trade show projects involving Hans Schröder Salowski.",
    titleGallery: "Gallery | Hansolow Entertainment",
    descriptionGallery: "A look at stage construction, touring, festivals and production environments.",
    titleContact: "Request availability | Hansolow Entertainment",
    descriptionContact:
      "Send a project inquiry for tour support, stage construction, event support or trade show construction. Availability on request.",
    titleImprint: "Imprint | Hansolow Entertainment",
    titlePrivacy: "Privacy | Hansolow Entertainment",
  },
  nav: {
    home: "Home",
    about: "About",
    services: "Services",
    experience: "Experience",
    gallery: "Gallery",
    contact: "Contact",
    items: [
      { label: "Home", href: "/en" },
      { label: "About", href: "/en/about" },
      { label: "Services", href: "/en/services" },
      { label: "Experience", href: "/en/experience" },
      { label: "Gallery", href: "/en/gallery" },
      { label: "Contact", href: "/en/contact" },
    ],
    ctaPrimary: "Request availability",
    ctaPrimaryHref: "/en/contact",
  },
  hero: {
    eyebrow: "Tour Support · Stage Construction · Event Support",
    title: "Hans Schröder Salowski",
    subtitle:
      "Freelance Stage Construction and Tour Support for Touring, Festivals, TV Productions and Trade Shows",
    tagline: "Based near Leipzig, Germany · Available nationwide and internationally",
    ctaPrimary: "Request availability",
    ctaPrimaryHref: "/en/contact",
    ctaSecondary: "View experience",
    ctaSecondaryHref: "/en/experience",
    trustItems: [
      "Available on a project basis",
      "Willing to travel",
      "Category B driving licence",
      "Forklift licence",
    ],
  },
  about: {
    eyebrow: "About",
    heading: "Stage construction with a clear process",
    paragraphs: [
      "Hans Schröder Salowski is a freelance stage construction and production support professional with practical experience in touring, event setup, festivals, TV productions and trade shows. His work focuses on reliable execution, clear workflows and structured load-ins, changeovers and load-outs.",
      "This includes operational support during rehearsals, shows and changeovers, as well as additional experience in trade show construction.",
      "He works on a project basis, integrates into changing crews and follows the requirements of stage, production and technical management.",
    ],
    factsHeading: "At a glance",
    facts: [
      { label: "Active since", value: "October 2024" },
      { label: "Coverage", value: "Nationwide, Europe-wide, international" },
      { label: "Availability", value: "On request, project by project" },
      { label: "Based near", value: "Leipzig, Germany" },
    ],
    approachHeading: "Way of working",
    approachItems: [
      "Reliable",
      "Structured",
      "Resilient",
      "Pragmatic",
      "Calm under pressure",
      "Team-oriented",
      "Flexible within changing crews",
      "Comfortable in time-critical production environments",
    ],
    ctaLabel: "Request availability",
    ctaHref: "/en/contact",
  },
  services: {
    eyebrow: "Services",
    heading: "Support for stage, tour and production",
    intro:
      "Project-based support across the full production timeline – from load-in to load-out, according to stage and production management requirements.",
    items: [
      {
        title: "Stage Construction",
        description: "Build and strike of stages and stage elements according to technical management.",
      },
      {
        title: "Tour Support",
        description: "Reliable support throughout a tour, from preproduction to the live show.",
      },
      {
        title: "Festival Support",
        description: "Stage construction and operational support in festival environments.",
      },
      {
        title: "TV Production Support",
        description: "Build and production support for TV productions and large-scale shows.",
      },
      {
        title: "Event Support",
        description: "On-site support for event setup and running order.",
      },
      {
        title: "Production Support",
        description: "Operational support during rehearsals, shows and changeovers.",
      },
      {
        title: "Stage Logistics",
        description: "Structured organisation of materials, pathways and workflows on stage.",
      },
      {
        title: "Load-in and Load-out",
        description: "Clean, efficient build and strike according to schedule.",
      },
      {
        title: "Changeovers during rehearsals and shows",
        description: "Fast, precise changeovers within a live production schedule.",
      },
      {
        title: "Backstage Operations",
        description: "Support for workflows in the backstage area.",
      },
      {
        title: "Event Setup",
        description: "Build and strike for events of any scale.",
      },
      {
        title: "Trade Show Construction",
        description: "Additional experience in building and dismantling trade show booths.",
      },
      {
        title: "Special Installations",
        description: "Custom builds based on specific project requirements.",
      },
      {
        title: "Lighting Support for touring, festival, TV and event productions",
        description:
          "Assisting tasks around stage lighting, carried out under the direction of the lighting department.",
      },
      {
        title: "Addressing and cabling of stage lighting fixtures",
        description: "Careful addressing and cabling of lighting fixtures on site.",
      },
      {
        title: "Setup and connection of lighting fixtures according to production specifications",
        description: "Mounting and connecting fixtures according to production requirements.",
      },
      {
        title: "Functional testing of individual fixtures using grandMA3",
        description:
          "Testing the function of individual fixtures using grandMA3, within the scope of Lighting Support.",
      },
      {
        title: "Verification of DMX, power and signal paths",
        description: "Checking DMX, power and signal paths for correct connection.",
      },
      {
        title: "Technical troubleshooting support within the scope of Lighting Support",
        description: "Assisting with technical troubleshooting in the lighting department.",
      },
      {
        title: "Support according to stage and production management requirements",
        description: "Dependable execution of clear instructions during live operations.",
      },
    ],
    note: "All services are provided on a project basis and in coordination with the relevant stage and production management. Lighting Support covers assisting, supportive tasks and does not include independently programming complete shows or operating the lighting console during performances.",
  },
  experience: {
    eyebrow: "Experience",
    heading: "Stage and Event Construction",
    intro:
      "Regular project-based work on touring productions, festivals, TV productions and major events.",
    roleTitle: "Stage and Event Construction",
    since: "since October 2024",
    roleDescription:
      "Regular project-based work in stage and event construction on touring productions, festivals, TV productions and major events.",
    tasksHeading: "Typical tasks",
    tasks: [
      "Stage Construction",
      "Stage build",
      "Changeovers during rehearsals and shows",
      "Stage logistics",
      "Load-in and load-out",
      "Support of technical workflows during the show",
      "Work according to stage, production and technical management requirements",
      "Support during preproduction and tour preparation",
      "Collaboration with changing national and international crews",
      "Lighting Support for touring, festival, TV and event productions",
    ],
  },
  references: {
    eyebrow: "Experience",
    heading: "Touring, TV Productions and Trade Shows",
    intro: "An overview of past project work. Further details and references available on request.",
    touringHeading: "Touring and Festivals",
    tvHeading: "TV Productions and Major Events",
    tradeShowHeading: "Trade Show Construction and Special Projects",
    tasksLabel: "Scope of work",
    onRequest: "References available on request",
  },
  skills: {
    eyebrow: "Skills",
    heading: "Skills and certifications",
    items: [
      "Stage Construction",
      "Tour Support",
      "Event Support",
      "Event setup",
      "Stage logistics",
      "Load-in",
      "Load-out",
      "Changeovers",
      "Teamwork within changing crews",
      "Working under time pressure",
      "Structured execution of instructions",
      "Pragmatic problem-solving",
      "Willingness to travel",
      "Lighting Support",
      "Addressing and cabling of stage lighting fixtures",
      "Functional testing of fixtures using grandMA3",
      "Verification of DMX, power and signal paths",
    ],
    certificatesHeading: "Certifications",
    certificates: ["Category B driving licence", "Forklift licence"],
  },
  gallery: {
    eyebrow: "Gallery",
    heading: "A look at stage and production work",
    intro: "Impressions from touring, festivals, TV productions and trade shows.",
    categories: {
      touring: "Touring",
      festivals: "Festivals",
      tv: "TV",
      stage: "Stage Construction",
      tradeshow: "Trade Shows",
      backstage: "Behind the Scenes",
    },
    all: "All",
    empty: "Images will be added shortly.",
  },
  contactPage: {
    eyebrow: "Contact",
    heading: "Request availability",
    intro:
      "For tour support, stage construction, event support or trade show construction – a few project details are enough for an initial response.",
    directHeading: "Direct contact",
    formHeading: "Send a project inquiry",
    availabilityLabel: "Availability on request",
  },
  form: {
    name: "Name",
    company: "Company",
    email: "Email",
    phone: "Phone",
    phoneOptional: "Phone (optional)",
    projectType: "Project type",
    projectTypeOptions: [
      "Touring production",
      "Festival",
      "TV production",
      "Major event",
      "Trade show construction",
      "Stage construction",
      "Other",
    ],
    location: "Event location",
    country: "Country",
    period: "Timeframe or dates",
    duration: "Estimated duration",
    scope: "Requested scope of work",
    message: "Message",
    consent:
      "I have read the privacy policy and agree to the processing of my details in order to handle this inquiry.",
    submit: "Send inquiry",
    submitting: "Sending …",
    successTitle: "Thank you for the inquiry.",
    successBody: "The details have been submitted. A response will usually follow by email shortly.",
    errorTitle: "Unable to send",
    errorBody: "The inquiry could not be sent automatically. A prepared email will open as an alternative.",
    requiredError: "Please fill in this field.",
    emailError: "Please enter a valid email address.",
    consentError: "Consent is required.",
    fallbackNote: "Alternatively, reach out directly by email or phone – details above.",
  },
  cta: {
    heading: "Planning a project?",
    body: "A few details on timeframe, location and scope are enough for an initial assessment.",
    primary: "Request availability",
    primaryHref: "/en/contact",
    secondary: "View services",
    secondaryHref: "/en/services",
  },
  footer: {
    tagline: "Tour Support · Stage Construction · Event Support",
    navHeading: "Navigation",
    contactHeading: "Contact",
    legalHeading: "Legal",
    imprint: "Imprint",
    privacy: "Privacy",
    rights: "All rights reserved.",
  },
  legal: {
    imprintHeading: "Imprint",
    imprintIntro: "Information according to § 5 TMG (German Telemedia Act).",
    imprintDraftNotice:
      "The details below are based on the imprint and privacy data provided by the website operator. A final legal review before publication is still recommended (see README).",
    privacyHeading: "Privacy Policy",
    privacyDraftNotice:
      "The details below are based on the imprint and privacy data provided by the website operator. A final legal review before publication is still recommended (see README).",
  },
  common: {
    skipToContent: "Skip to content",
    languageSwitchLabel: "Switch language",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    callUs: "Call",
    emailUs: "Send email",
    instagram: "Instagram",
    backHome: "Back to homepage",
  },
};
